name: 'Docker Install'
description: 'Installs Docker engine on the runner (for self-hosted runners without Docker).'

runs:
  using: 'composite'
  steps:

    - name: 🐋 Set up Docker
      shell: bash
      run: |
        sudo apt-get update
        sudo curl -fsSL https://get.docker.com -o install-docker.sh
        sudo sh install-docker.sh
        sudo usermod -aG docker $(whoami)
        sudo chmod 666 /var/run/docker.sock
        docker --version
